PLANTILLA EJEMPLO PL PROCEDURE

PROCEDURE NOMBREPROC(VARIN1 IN NUMBER,--PUEDE USARSE IN OUT A LA VEZ
                VAROUT1 OUT VARCHAR,
                VAROUT2 OUT VARCHAR)
IS
--DECLARAR VARIABLES AQUÍ!.. las de OUT ya están declaradas! 
V_VAR_A         VARCHAR2 (20);
V_EXCEPCION_A  EXCEPTION;
V_NUMERO_A       NUMBER;
BEGIN
VAROUT1:='DEFAULTVALUE'; --ASIGNAMOS DIRECTAMENTE O CON INTO EN UN SELECT

    SELECT FIELD1, FIELD2
    INTO
    VAROUT1, VAROUT2 -- PARA ASIGNAR LA SALIDA DEL SELECT EN ALGUNA VARIABLE1
    FROM TABLE1
    WHERE X=Y
    
    EXCEPTION --VA DENTRO DE UN BEGIN-END SIEMPRE!
    WHEN NO_DATA_FOUND THEN --USADA EN SELECT
    --ALGO (LOG, METODO, ASIGNAR ERROR AL OUTPUT, ETC)
    RAISE V_EXCEPTION_A;

EXCEPTION
WHEN V_EXCEPTION_A THEN --SI ARROJO ANTES CON     RAISE EXCEPCION_A;
   --ALGO
WHEN OTHERS THEN --ALGUNA OTRA EXCEPTION NO DECLARADA
    --ALGO
    --COMMIT;
    --ROLLBACK;
END;               
END NOMBREPROC;    